// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateCarnet(ctx context.Context, arg CreateCarnetParams) (Carnet, error)
	CreateKid(ctx context.Context, arg CreateKidParams) (Kid, error)
	CreateKidNote(ctx context.Context, arg CreateKidNoteParams) (KidNote, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	CreateTeacherNote(ctx context.Context, arg CreateTeacherNoteParams) (TeacherNote, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, email string) error
	GetAllCarnets(ctx context.Context) ([]GetAllCarnetsRow, error)
	GetAllKidNotes(ctx context.Context) ([]KidNote, error)
	GetAllKids(ctx context.Context) ([]Kid, error)
	GetAllTeacherNotes(ctx context.Context) ([]TeacherNote, error)
	GetAllTeachers(ctx context.Context) ([]Teacher, error)
	GetCarnet(ctx context.Context, id int64) (Carnet, error)
	GetKid(ctx context.Context, id int64) (Kid, error)
	GetKidNote(ctx context.Context, id int64) (KidNote, error)
	GetKidNotesByPeriod(ctx context.Context, arg GetKidNotesByPeriodParams) ([]GetKidNotesByPeriodRow, error)
	GetTeacher(ctx context.Context, id int64) (Teacher, error)
	GetTeacherNote(ctx context.Context, id int64) (TeacherNote, error)
	GetTeacherNotesByDate(ctx context.Context, date time.Time) ([]GetTeacherNotesByDateRow, error)
	GetTeacherNotesByPeriod(ctx context.Context, arg GetTeacherNotesByPeriodParams) ([]GetTeacherNotesByPeriodRow, error)
	GetUser(ctx context.Context, email string) (User, error)
	UpdateCarnet(ctx context.Context, arg UpdateCarnetParams) (Carnet, error)
	UpdateKidNote(ctx context.Context, arg UpdateKidNoteParams) (KidNote, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (TeacherNote, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
