# Build stage
FROM golang:1.19.2-alpine3.16
WORKDIR /app
COPY . .
RUN apk update; apk add curl
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
COPY serviceAccountKey.json ./serviceAccountKey.json
COPY app.env.compose ./app.env
COPY start.sh .
COPY wait-for.sh .
COPY db/migrations ./migrations
EXPOSE 8080
RUN ls
CMD ["air", "run", "main.go"]
ENTRYPOINT ["/app/start.sh"]